### ISSUE TITLE
If number of guests filter is set, profiles which haven't specified a max number are not included in results

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#1247]
I think they should be, right?

**Comment by aapeliv** [comment]
I imagine the max guests feature will be used mostly by people who travel in big groups: and I imagine it's more common for people to be able to host 1 person than groups. So I imagine it would get annoying for if you're trying to surf as a group of 3 and 90% of the people can't host you but show up because they didn't specify a max guests?
