### ISSUE TITLE
You can leave references with no text

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#1274]

**Comment by lennartvanlaake** [comment]
From the title of this issue and the fact that this is assigned to backend I assume that @lucaslcode expects BE to throw an exception if the text of a referece is empty (or contains entirely of whitespace?). 

@aapeliv is that the way references should work? I can imagine that the 'reference' object can be used in the future just contain a rating without having an explicit text. If that would be something we consider, I would suggest that doing the validation on empty reference text should be in the frontend, since on the frontend we can be more flexible about whether we always want to have this text or not. Also, you can probably alert the user in a nicer way that their reference text should be filled in.

**Comment by lennartvanlaake** [comment]
Changing the status to 'wontfix' for now until we have a final decision on how we want to handle empty reference text.

**Comment by aapeliv** [comment]
> From the title of this issue and the fact that this is assigned to backend I assume that @lucaslcode expects BE to throw an exception if the text of a referece is empty (or contains entirely of whitespace?). @aapeliv is that the way references should work?

Yes, I think it should be done that way.

>  I can imagine that the 'reference' object can be used in the future just contain a rating without having an explicit text. If that would be something we consider, I would suggest that doing the validation on empty reference text should be in the frontend

If we change it in the future, we will have to update both backend and frontend regardless. The final onus on validation is on backend; anything frontend does is just a courtesy and for UX. If we change references to eventually not require text; then that should have text be NULL, not an empty string, and they'll probably require a bunch more updating elsewhere too. In this situation I'd say it's better to design/implement for the current use case; it's not like removing that check if we decide to implement rating-only refs is a huge architectural decisions.

**Comment by lucaslcode** [comment]
Additional note, backend can't trust the frontend for validation since the API is public

**Comment by lennartvanlaake** [comment]
Sure, will fix it. If you are not interested in taking part in a discussion on software-design theory, stop reading here ;)



On a principal basis I would disagree on the necessity of this. I would say that a backend should validate things that are intrinsic to the consistency of an entity. For instance, without a user to which a reference is directed, a reference is not a reference, so backend should definitely check that. A reference with its text set to an empty string would not be inconsistent IMO, just somewhat useless. 

In practice that idea would mean that if someone would bother to bypass our frontend to leave an empty reference, that would only lead to that reference being ugly and the person receiving that reference thinking that user is weird. I would say that is an acceptable consequence.

**Comment by lucaslcode** [comment]
Counterpoint, if someone decides to make a Couchers client and people start using it (like Reddit), but they don't implement all the same frontend checks, we start getting our client and backend polluted with ugly objects.

Alternative counterpoint, the design states that there is a private part to the reference (rating, was appropriate) and a public part (the text), having the text blank is violating the design.

**Comment by lucaslcode** [comment]
Or worse, the alternative client has a bug - users enter the text, but an empty string is always sent to the backend!

**Comment by aapeliv** [comment]
> On a principal basis I would disagree on the necessity of this.

Why do you think so?

I really think the backend should be validating not only db-level consistency but also business logic–level rules.

This also makes our life easier: we will soon be supporting 3 platforms, and having final business logic checking in the backend will make our lives easier if we fail to do something in one of the frontends.

> I would say that is an acceptable consequence.

Are you sure? I think it'd be pretty bad to have a bunch of "ugly" objects in the db, and users opening bugs because the "reference wasn't loading"!

**Comment by lennartvanlaake** [comment]
> I really think the backend should be validating not only db-level consistency but also business logic–level rules.

I would draw the destinciton not between db-level/business logic but between 'is this intrinsic to the conceptual entity or not'. If we would take this a step further, we could say that a refrence below 10 characters would be bad and something we want to discourage, but it would still be a 'valid' reference, since it has all the properties necessary to process it, display it and execute any methods on it that we have. In that case I would argue that it is fine that the validation/"discouragement" of having very short refrences happens in the frontend, particularly when bypassing the frontend would exclusively mess up entities owned/created by the one messing with our frontend.

> Counterpoint, if someone decides to make a Couchers client and people start using it (like Reddit), but they don't implement all the same frontend checks, we start getting our client and backend polluted with ugly objects.

Well, if someone decides to mess with our designs and then write ugly content in our entities, I would not spend too much time on making sure that their UI keeps looking prefect. 

> Alternative counterpoint, the design states that there is a private part to the reference (rating, was appropriate) and a public part (the text), having the text blank is violating the design.

Yeah, I get that in this case we would say that it is part of our definition of a 'reference' that it has non-empty text, since our design might break if we have empty text. My main point would be that the "is it part of a defintion"-check should be the bar for backend validations, rather then always duplicating all validations on frontend and backend, so would be a valid reason forme.

**Comment by aapeliv** [comment]
Simplicity and consistency is key. We want to not have to think case-by-case about what gets validated in the bg vs fgs. We now have two levels of validation logic: db-level and business logic–level. We don't want a third level somewhere in the middle. We want as few combinations of everything as possible. Sure, it doesn't lead to edge cases that crash the app, but it does lead to edge cases that are "buggy" and cause bad user experience (e.g. getting an email that says `Aapeli just wrote you a reference, they said: ""` just looks buggy and will be reported by users).

What about display names? It's exactly the same. People will definitely think the app is buggy and crappy if there are users without a display name. That'd also lead to visual bugs, and we don't want the frontend to be coding a bunch of stuff that says `displayName.length > 0 ? displayName : 'Missing name'`, because that's what they'll be forced to do if we start having these kinds of things happen.

> particularly when bypassing the frontend would exclusively mess up entities owned/created by the one messing with our frontend

So the programming decision of where to do the checking would be "if the entity being messed up only affects the user themselves, then defer it to the frontend, otherewise consider whether it's required for the consistency of the entity in some abstract sense, if so, then add a backend check as well"? It's way too complicated and will lead to bugs.

Also, a user writes references to other people: it shows up in the other user's page, so it messes up "their" page.

> My main point would be that the "is it part of a defintion"-check should be the bar for backend validations, rather then always duplicating all validations on frontend and backend, so would be a valid reason forme.

Again, the backend *is* the validator and handles the business logic. The frontend stuff is just there to catch obvious things to reduce extra network requests (reducing feedback loop time for user) and make the user experience easier (e.g. easily catching an email that looks wrong, etc).

**Comment by lennartvanlaake** [comment]
> So the programming decision of where to do the checking would be "if the entity being messed up only affects the user themselves, then defer it to the frontend, otherewise consider whether it's required for the consistency of the entity in some abstract sense, if so, then add a backend check as well"? It's way too complicated and will lead to bugs.

So, I think that is a conceptual difference in thiking about software. I would say that ideally first you have an abstract idea of an entity (a user, a reference, etc), which is then translated to flows and designs and eventually to software. That concept of a reference should not change often, while some aspects of what people do with references or how we show them will change a lot more often. Based on that concept you know which things we will always asume that the entity will have (in this case a reference will always have text, a user it is sent to, a reference giver, a (valid) date...) which we can assume will always be true so we can take them for granted in our software.

 The 'harm' in doing duplicate checks on backend and frontend is that you duplicate business logic, which means that they can start differing from eachother, leading to a buggy experience. Clearly the harm of this duplication is outweighed by the benefits of backend-checks when it comes to corrupt data or safety, but if there is the check is more of a design addition then I don't think that is the case. 

 To me this is somewhat of a border-line case, so I'm not arguing about this specific case ;) And I get that within the couchers we draw the line on 'backend does all validation'. I was just starting a flame-war on this because to me it is a nice example to talk about software design philosophy.

**Comment by aapeliv** [comment]
> That concept of a reference should not change often ... things we will always asume that the entity will have

You're designing for some future concept of what a reference is. There is no pure, immutable, abstract concept of what a reference is. I guarantee you, that list of things you've listed will change in some way or another. We will change something, we will add fields, the data will change. Trying to come up with an abstract immutable version and then "the current version" as two separate concepts will just cause problems in the future, and cause unnecessary splitting of hairs.

We need to strike a balance between designing for what we need now (current version) and extensibility (being able to add what we might reasonably wish to add). It's quite rare in CRUD apps, in particular with these basic models, that you need to consider extensibility too much. Extensibility really comes when you're trying to design a feature as a whole and the structure of tables, etc; not so much for these kinds of fields that go within them.

I have personally found — time after time — that as software engineers (or at least those of us who enjoy the abstract pleasures of architecture/systems design), we tend to often overcomplicate systems for the future. And I've found time after time that defining beforehand exactly what data needs to look like and having strict validation and definitions, and then putting effort into the migrations when they happen seems to be the way to go.

> The 'harm' in doing duplicate checks on backend and frontend is that you duplicate business logic, which means that they can start differing from eachother, leading to a buggy experience.

There's really no way around it. In the end, we'll still need to keep things in sync. But the source of truth should be the backend.

**Comment by lennartvanlaake** [comment]
I think we can best agree to disagree here, since I feel that we are going in circles a bit and I am  not disputing the call in this particular instane. Woud still be happy to talk about this a bit mroe when we have 

> We need to strike a balance between designing for what we need now (current version) and extensibility (being able to add what we might reasonably wish to add). It's quite rare in CRUD apps, in particular with these basic models, that you need to consider extensibility too much. Extensibility really comes when you're trying to design a feature as a whole and the structure of tables, etc; not so much for these kinds of fields that go within them.

This comment scares me a little bit. I think what we currently have is moving quickly beyond a 'simple CRUD' app. I am afraid that not having clear definitions of what entity is reponsible for containing which information is going to lead to heaps of trouble. If I look at the 'User' table and I see that one entity has the users name and a boolean 'wheelchair_accessable' on the exact same level, I am a bit worried about the scope of what we believe that entity should be responbile for.

Anyhow, I will get back to doing actual things now. I think it is good to have discussions like this on our software design philosophy, so thanks guys for joining in <3
