### ISSUE TITLE
My Profile Buttons

### ISSUE THREAD

**Issue by dommers-ux** [Couchers-org/couchers#1322]
Upon selecting **Profile**, the buttons should be the same color palette (i.e. one should not be orange, and the other be teal).  
There should be a hierarchy of buttons (actions). To establish differentiation, we can implement the primary vs. secondary button style: 

- Before - 
<img width="346" alt="Screen Shot 2021-05-29 at 10 30 58 PM" src="https://user-images.githubusercontent.com/83376913/120090492-e7d29400-c0d0-11eb-8a51-964fc10357f7.png">

- After - 
<img width="253" alt="Screen Shot 2021-05-29 at 10 35 31 PM" src="https://user-images.githubusercontent.com/83376913/120090496-eef9a200-c0d0-11eb-941d-52f63338bbb9.png">

Overall, it's cleaner and creates a hierarchy. It's also consistent with the primary color of buttons.

**Comment by dommers-ux** [comment]
Oops - I forgot to mention. The buttons are extended to their own row to increase accessibility / reachability.

**Comment by thdk** [comment]
I was developing this with the following figma design in my mind:

![image](https://user-images.githubusercontent.com/4201102/120105563-be117f80-c159-11eb-8d83-e37bac241199.png)

Where I assume the my connections button would eventually be removed to a separate card below the profile overview? 

![image](https://user-images.githubusercontent.com/4201102/120105619-f749ef80-c159-11eb-80b3-f5e25f9c207e.png)

That's why I made the edit button orange.

**Comment by dommers-ux** [comment]
(Ignore my initial post).
