### ISSUE TITLE
"Map search" should just be "search"?

### ISSUE THREAD

**Issue by ShmuelTreiger** [Couchers-org/couchers#1628]
Unless/until we have a separate search mechanism, calling it "map search" seems confusing to me?

**Comment by aapeliv** [comment]
It's just to highlight there's a map behind there

**Comment by ShmuelTreiger** [comment]
Maybe add it in parentheses? Like "Search (Map)"

Just now, I went to the website, went looking for search and was like "woh, that's weird". Seems confusing to me as an average user of the frontend

**Comment by jesseallhands** [comment]
The current desktop version doesn't match the design we should be aiming for:

![image](https://user-images.githubusercontent.com/79384268/125362551-b508f600-e334-11eb-96ff-040174c06cae.png)

Since right now you can only search for people/places/keywords, we could change the text prompt for the search bar.
Typing in text and pressing enter to search (or clicking the search symbol) would take the user to the map with the results.

**Comment by ShmuelTreiger** [comment]
Agreed, but for now this is a quick fix

**Comment by aapeliv** [comment]
It's important to have the word "map" and "search" both in the same text there. I think parentheses just add clutter.

The current navbar requires a lot of other work, including the search bar, etc. We will have to work on it later when the omnisearch is built out.
