### ISSUE TITLE
Add warning when leaving a page with a dirty form

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1635]
Is there a way to do this easily with our react-hook-form?

**Comment by lucaslcode** [comment]
[Yes](https://react-hook-form.com/v6/api#formState)
```
const { control, errors, formState, register } = useForm();
const { isDirty } = formState;
// isDirty is true if any fields are modified
```
@kerryja helpful for your issue

**Comment by kerrylaval** [comment]
@lucaslcode @Couchers-org/frontend I started on this by using the `formState` to check `isDirty`. It is working as expected initially when the form loads and is returning false. However, it then starts returning true without me changing anything. It looks like it is because all of the form fields need to have defaultValues set in `useForm`. Right now there are only 4 default values defined. I see that there are also default values added to each of the controllers, so how should I connect them? Here is what I have so far https://github.com/Couchers-org/couchers/compare/develop...kerryja:frontend/feature/dirty-form-detection

**Comment by aapeliv** [comment]
Could we somehow include this automatically for all forms? Are there cases of forms where we'd not like this feature?
