### ISSUE TITLE
Flaky tests on develop again

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1801]
https://gitlab.com/couchers/couchers/-/pipelines/349886838

https://gitlab.com/couchers/couchers/-/pipelines/351220413

**Comment by lucaslcode** [comment]
So I *think* essentially we are seeing performance issues rather than mistakes in our tests.

There is a lot of discussion [here](https://github.com/testing-library/dom-testing-library/issues/820) and also see this interesting PR from [this project](https://github.com/Recidiviz/public-dashboard/pull/379/files). Basically:

- JSDom is slow
- many of the recommended `react-testing-library` queries are slow
  - particularly `getByRole` but there is a lot of benefit to using this
- large dom trees are slower to test on
- lots of tests in a single file [might be worse](https://github.com/testing-library/dom-testing-library/issues/820#issuecomment-878406132)?

`getByRole` can be improved by setting `visible: false` to not test visible roles, but that makes for worse testing. Not using `{ name }` and instead testing the content separately might see some improvements.

I don't know if there's a way to use puppeteer or something other than JSDom which would presumably help. It doesn't seem like it from a quick search.

@darrenvong thoughts?

**Comment by darrenvong** [comment]
Some pretty good findings there! Based on what I mentioned in our meeting, I think splitting the test files up first to avoid a large test suite seems like the easiest thing to try first. It'd allow us to do away with less `describe` nesting as well which [Mr Dodds seems to recommend](https://kentcdodds.com/blog/avoid-nesting-when-youre-testing), so we could potentially improve reliability and test readability at the same time if this alone works?

Then I'd probably go with these until things stabilise (roughly ordered):
- More unit tests lower down the component tree to break up the DOM tree
- Check for text content separately from the `getByRole`
- Set `visible: false`
- (Probably last resort) Look into bundling the test suite and run it in headless Chrome as suggested [here](https://github.com/testing-library/dom-testing-library/issues/820#issuecomment-760524317)?

Hopefully doing these wouldn't reduce the confidence the tests are supposed to give us too much.

**Comment by lucaslcode** [comment]
Is it just me or did it un-flake itself?

**Comment by darrenvong** [comment]
Yeah it seems to be fine for me lately too

**Comment by aapeliv** [comment]
OK, closing
