### ISSUE TITLE
Add events from my communities to the dashboard.

### ISSUE THREAD

**Issue by ItsiW** [Couchers-org/couchers#1880]
Include a component on the dashboard that shows all events from communities the user is a member of, in chronological order. Placed underneath the communities section

**Comment by lucaslcode** [comment]
We need a design for this

**Comment by ItsiW** [comment]
There is a design on figma for this component on the dashboard. Otherwise we could use the same design as is currently implemented for a specific community, with the addition of a label on each event that says which community it comes from

**Comment by darrenvong** [comment]
It'd be good if there's a new rpc for this too at some point? Otherwise this would end up being one API call per community which probably isn't great for the backend and it's gonna get slow real quick (although maybe not an immediate concern since people probably aren't in that many communities yet)

**Comment by ItsiW** [comment]
Yeah definitely, and I imagine we'll also want to do something like this for discussions as well, but the order we show them  in might need a bit more thinking out

**Comment by darrenvong** [comment]
Finally started looking into this a bit and... this is going to be impossible to implement without a new API because:
- The list of user communities is paginated (from the `ListUserCommunities` rpc), which means there's no way for the frontend to know all the communities the user is part of, since it's impossible for it to know how many pages of communities there will be (it's dynamic and shouldn't be the frontend's job to figure that anyway);
- Even if we sidestep the above and do it based on "best effort" (i.e. only display events from the first X page of communities the user belongs to), issuing one `ListEvents` rpc call per community is going to result in events all jumbled up and only sorted chronologically per community.
- Since the `listEvents` rpc call also returns a paginated list of events... we have the same issue here as `ListUserCommunities`. AND since `react-query` doesn't have `useInfiniteQueries` (plural), I think this is impossible to do, since we need to conditionally figure out (i.e. breaks the rule of hooks) the number of `ListEvents` calls based on the number of communities a user is in

**Comment by darrenvong** [comment]
Without changing the backend, I think a reduced version of this would probably be up to 25 events from all loaded communities so we don't worry about getting events beyond the first page of `ListEvents` per community. Maybe that's good enough?
