### ISSUE TITLE
Communities navigation component

### ISSUE THREAD

**Issue by ItsiW** [Couchers-org/couchers#1881]
There are now too many communities to easily navigate via the list. It would be good if we could do something like nested drop-downs that show sub-communities

**Comment by darrenvong** [comment]
This could theoretically get very deeply nested and gets complicated (hence we avoided it in discussions?), so not sure a simple nested pattern is a good idea. Or we could cap at a certain depth, but then not all communities will be reachable if we do that. Might need some design inputs on how to show this so all the communities are still reachable?

**Comment by dommers-ux** [comment]
this is on our meeting agenda for our next UX meeting. a few ideas have been discussed before but a final decision has yet to be made

**Comment by ItsiW** [comment]
I think this component is still a temporary fixture of the dashboard, we want to make it prominent so people can get a good idea of what communities need to be started. Long term we may want a separate page  for community navigation that's well thought out, but it's probably fine as something simple for now

**Comment by darrenvong** [comment]
Yeah that's a good point, most code in the dashboard is probably at the throwaway category in my head at the moment, as we haven't the time/resource to finalise/started doing things closer to the Figma designs yet due to other competing features. So maybe for this initial version, we shouldn't waste too much time over thinking it and focus on getting something out instead. 

But it would still be good to see a design for it in the longer term of course, so nice to hear it will be discussed in a UX meeting soon

**Comment by lucaslcode** [comment]
I think deep nesting is fine, we can just only load one level at a time.
