### ISSUE TITLE
When signingup, and person do not want to contribubte, the form below should hide

### ISSUE THREAD

**Issue by goskan93** [Couchers-org/couchers#1885]
![image](https://user-images.githubusercontent.com/39600021/131211803-9f6a1355-d404-45be-904d-9f74c2316dc5.png)

**Comment by lucaslcode** [comment]
This was the behaviour and I believe @ItsiW changed it?

**Comment by ItsiW** [comment]
We have a lot of people that say no but then offer skills, so the question is not clear to people or they re-think it after the prompt. Most people who aren't interested in helping just skip the section altogether. It's probably worth keeping as is even though it's not amazing ux for some people

**Comment by goskan93** [comment]
I would say, that is why the option 'Maybe' is for. When person clicks 'No' and the form stills appears, it feels like their choice is not respected. In my opinion, if we would like to encourage people to contibute, we could mark at first place the 'Yes' option, and then let people decide if they want to fulfill the form, or choose 'No' option.

**Comment by ItsiW** [comment]
It's a good approach but we want it by default to be squished down, both because most people want to skip the section altogether, and because showing all those questions at once would dissuade people from answering. I think it's fine for now, people are fairly bug-tolerant at this point and know they can skip all of this, and we have sufficient people that do answer no but fill it in for us to want to keep it like this
