### ISSUE TITLE
Last markdown field is automatically focused on profile/home edit page

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#1887]
Reproduced on chrome windows and android.

**Comment by darrenvong** [comment]
It's because of this https://github.com/nhn/tui.editor/blob/f0bc7cc6bbed33d8e8c7e2a9e72be64e8a6c083e/apps/editor/src/editorCore.ts#L284... which is a bit annoying since that means the markdown field will always steal focus.

I wonder if we should file something to their repo to make this behaviour configurable (i.e. don't focus on initialisation of the editor), otherwise the only thing we can do is call focus on the first field of our form again, but not sure how reliable of a fix that'd be as there could be a race condition... but might be good enough as a workaround if it works?

**Comment by lucaslcode** [comment]
Looks like there is a recent open PR
https://github.com/nhn/tui.editor/pull/1772

**Comment by aapeliv** [comment]
@darrenvong was this closed in f5657a92aecf24d3dd65f0bcde642f2e43b56966?

**Comment by darrenvong** [comment]
No, still need to make a change to set the `autofocus` option to `false` first in the `ToastUIEditor` constructor config to fix this.

**Comment by thdk** [comment]
I can add this option to stop autofocus these markdown fields.
