### ISSUE TITLE
Cannot edit event while event is going on

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#2005]
I tried editing my event while it was going on (I was updating information on where our table is located on the lakeside terrace) and it wouldn't let me update it. I got an error "The event start time must be in the future" and it highlighted the start time.

You should be able to update the event up until the event is over (or perhaps until the end of the day since sometimes events go longer and you may need to provide an update). This is especially true for multi-day events.

The event this happened to is here:

https://app.couchers.org/event/285/happy-hour-social

**Comment by darrenvong** [comment]
I think this might actually be the web frontend's fault, since it sends all of the field's values back in the update request even though you might not have changed them, so the backend thinks you are trying to update the event to a time in the past.

This is fine when you're creating a new event from scratch, but I guess not good when you only want to edit and the start/end date/time fields are time sensitive.
