### ISSUE TITLE
"request" button still appears even if the person has "can't host" selected

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#2713]
We should not be displaying the "request" button if the person has selected "can't host". Right now the button appears like normal despite the "can't host" status and people are complaining to the support team because they are getting requests even though they indicated they cannot host:

![image](https://user-images.githubusercontent.com/79384268/159370501-5ecb4780-e1fc-44ad-9bd4-abda25a92c07.png)

**Comment by mketer1** [comment]
Hi! I'm fairly new to open source contribution but would love to try and tackle this problem. If this issue is still available, could I be assigned to it?

**Comment by lucaslcode** [comment]
@mketer1 please do! Let me know if you need any guidance

**Comment by mketer1** [comment]
@lucaslcode thank you for assigning the issue to me. I have been following the "setup tuturial" (https://github.com/Couchers-org/couchers/blob/develop/docs/contributing.md) in order to create a branch and to ensure that I can run it locally.

I have pulled the code and created a branch (web/improvement/request-button). I plan on working regularly starting this weekend as school may take up a good chunk of the remaining week.

Thank you for such a clear and concise contribution.md. I do have a few questions before getting started that I'd like to clarify.

1) When working on this project, what would be the prominent way to test functionality of my code? I understand that we're working in the develop branch so I obviously can't go to the production website right now. I was just wondering how I could test a feature that incorporates frontend development to ensure functionality

2) Is there a link in order to join the slack groupchat? I'm fairly new to open source contribution and would love to communicate with others who are much more familiar with this repository than I am in order to get pointers and assistance.

Thank you so much! I look forward to hearing from you!

**Comment by lucaslcode** [comment]
@mketer1 You can read how to get the dev environment running at [app/readme.md](https://github.com/Couchers-org/couchers/blob/develop/app/readme.md) and [app/web/README.md](https://github.com/Couchers-org/couchers/blob/develop/app/web/README.md). Let me know if it still isn't clear.

The slack is just for internal use, but feel free to ask anything here, or you can email me.

**Comment by dommers-ux** [comment]
Hi @mketer1 , 

Have you started tackling this problem? I'd like to provide a design for this issue. The **Request** button frame should be changed to have neutral colors: neutral gray text (#C4C4C4) and light gray fill (#E9E9E9). 

Also, the shadow effect should be removed, eliminating the perception it is a clickable button. 
See below for a visual example:

<img width="246" alt="Screen Shot 2022-03-28 at 4 49 15 PM" src="https://user-images.githubusercontent.com/83376913/160493321-6deb8744-a201-4360-afa5-2572d7207e32.png">

The text has also been changed to "**Can't host**" to communicate to viewers why the button is not interactive. However, if it is simpler to just leave the text "**Request**", no worries (will be addressed later).

**Comment by Tay0108** [comment]
I'll probably take care of it on Sunday/Monday so if @mketer1 you would have it done before me feel free to submit PR ;)
