### ISSUE TITLE
Background (cron/timed) jobs

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#282]
We need some way to run asynchronous background jobs, there's a few use cases:

* Sending emails in background with retry/backoff (currently it's pretty fast since it hits AWS SES through SMTP in the same region as the VM)
* Checking if users have not read their messages (after some time) and we should send them an email about missed messages
* Possibly nagging half-signed up people to sign up, etc
* Pruning things like expired signup/login tokens from the database

This doesn't need to be super fast/accurate, as long as stuff gets done within some seconds of being scheduled (for async jobs), etc.

Who knows of a good way of doing this? I've some ideas but want to hear what others think too.

**Comment by aapeliv** [comment]
@NightTsarina  and @shuttle1987, do you have opinions/wisdom for this?

**Comment by shuttle1987** [comment]
In the past the way I have gone about these sorts of things is to have a message queue that you can pass off tasks to be processed in the background. When a task is submitted to the queue there is response immediately with a URL or some other unique identifier for tracking the task that was just created. The processing of the task is then done asynchronously in a different process that is possibly on a different machine. Conceptually the simplest thing is to have some form of polling to see if new tasks have been completed. There's other architectures that an be used as well for this where the message queue pushes notifications out in some sort of publish-subscribe system.

Having something to execute tasks, especially emails, in the background is a very good idea.

I've personally enjoyed using [ZeroMQ](https://github.com/zeromq/pyzmq) for the messaging in these sorts of situations as it allows you to make the messaging architecture that your project needs. Though better alternatives that I am not aware of might exist now. The message queue system provided by [cloud platform] might be a good option depending on how much vendor lock-in the project is willing to take on and how good [cloud platform]s offering is. I'd avoid AMPQ for sure since that's not a very good protocol. I have used Celery in some previous production projects along with Flower to have monitoring, but there's some very weird bugs (like unbounded memory growth) when using Celery with some brokers that used to be almost impossible to debug. Again I'm possibly a couple of years out of date, those bugs hopefully have been fixed by now.

**Comment by kalvdans** [comment]
> Sending emails in background with retry/backoff

We could use exim4 for this. It accepts mails to a queue immediately and relays to a smarthost whenever it can reach it.

**Comment by kalvdans** [comment]
> Pruning things like expired signup/login tokens from the database

Can be done lazily at next access. This is already reported as issue https://github.com/Couchers-org/couchers/issues/65 .

**Comment by NightTsarina** [comment]
> We need some way to run asynchronous background jobs, there's a few use cases:
> 
>     * Sending emails in background with retry/backoff (currently it's pretty fast since it hits AWS SES through SMTP in the same region as the VM)

I think this is a job for a full-fledged MTA, and I would suggest postfix for that (Exim is not really great in my experience).

>     * Checking if users have not read their messages (after some time) and we should send them an email about missed messages
>     * Possibly nagging half-signed up people to sign up, etc
>     * Pruning things like expired signup/login tokens from the database

These are typical jobs to run at night once in a while. I think there are two obvious solutions:
* Have a CLI tool that does it, and set up a cron job. Easy and simple. The main drawback is that you have no state about the run, unless you specifically save something in the DB.
* Use a queue manager with pre-scheduled tasks, like `celery-beat`, but I find that cumbersome and another source of things that can go wrong. Since there is no need for a queue manager now, I would not add it just for nightly jobs.

**Comment by amdwit** [comment]
I would go for some micro-services connect by a messaging system. Or maybe just micro services, without messaging.

**Comment by aapeliv** [comment]
Regarding mail delivery:

I don't see the benefit of pulling in a full-fledged MTA to deliver mail. It would end up being yet another service we have to maintain, spin up during dev, and get new devs acquainted with. I don't see the benefits when added on top of [AWS SES](https://aws.amazon.com/ses/). SES already does retry with backoff on soft bounces.

The reason I've moved it into a background job in the PR is because the request to SES still takes a few moments sometimes. The backoff and retry on the bg job PR is mainly for general purpose jobs.

**Comment by kalvdans** [comment]
> The reason I've moved it into a background job in the PR is because the request to SES still takes a few moments sometimes.

Sounds like AWS SES is our full-fledged MTA then. Let's unlock the database before we send the e-mail so that the few moments it takes to hand off the email won't bother anyone.

**Comment by aapeliv** [comment]
> > The reason I've moved it into a background job in the PR is because the request to SES still takes a few moments sometimes.
> 
> Sounds like AWS SES is our full-fledged MTA then. Let's unlock the database before we send the e-mail so that the few moments it takes to hand off the email won't bother anyone.

It takes a noticeable amount of time (up to a few seconds). (This is also a security issue for account enumeration.)

Why do you object to passing off the connection to SES to a background job? I think it's clearly a thing that needs to be done in the background.

**Comment by kalvdans** [comment]
> Why do you object to passing off the connection to SES to a background job? I think it's clearly a thing that needs to be done in the background.

Since we run production on Amazon, the AWS SES is always up whenever we are up. So we could treat it as a reliable microservice and don't need to special case when it isn't accessible. And since there's no reason for it to be slow, we shouldn't design MTA slowness into our app. We better bug report to them when it is slower than it should or get our money back for lack of service.

[EDIT] We could hide the latency from the client by first replying to the client and then sending the email. Other threads in the thread pool will take care of new rpc requests while the email is being sent.

**Comment by aapeliv** [comment]
> Since we run production on Amazon, the AWS SES is always up whenever we are up.

Sure, though EC2 and SES are quite different services and have different uptimes. If we can be resilient to this, why not?

> And since there's no reason for it to be slow, we shouldn't design MTA slowness into our app.

But it is slow... so we should do something about it.

> We better bug report to them when it is slower than it should or get our money back for lack of service.

It's not sold as a particularly fast service.

> We better bug report to them when it is slower than it should or get our money back for lack of service.

We are unfortunately a rounding error in their rounding errors. We have no power to change the service.

> [EDIT] We could hide the latency from the client by first replying to the client and then sending the email. Other threads in the thread pool will take care of new rpc requests while the email is being sent.

This is essentially what the background job PR does: it passes it off to a queue of jobs to be done asynchronously.

**Comment by kalvdans** [comment]
> But it is slow... so we should do something about it.

No, we should not add extra technical dept to workaround bugs at one specific cloud provider.

But separating off the email sending to a different process is a good separation, it simplifies the servicers.

**Comment by aapeliv** [comment]
Closed in #479
