### ISSUE TITLE
Consider redux alternatives (or not)

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#399]
We originally went with Redux due to it's ubiquity, however it is certainly a bit cumbersome, although redux-toolkit helps a lot.

Here are some of the issues (please add):

1. Doesn't handle async natively very cleanly (requires thunks)
2. The store is global, and when to use component state vs the store is not always clear-cut
3. It has it's own code-feel/style that feels slightly alien to react (maybe that's more my opinion)
4. Difficult to learn

#### Keep redux

- This would avoid refactoring time (though perhaps now would be a good time anyway)
- Any new volunteers are more likely to have used redux than any other form of state management

#### mobx-state-tree

- It deals with async much better
- It keeps redux benefits like time-travel
- Much cleaner/less-boilerplate
- It is also somewhat difficult to learn, with the added drawback that far fewer people will have already used it compared to redux
- It also has the same problem 2 as redux.

#### `useReducers`

- AFAIK this is basically redux, but scoped. Not so sure about this.
- Would probably introduce more boilerplate than redux-toolkit
- This is the only option I am personally against 

#### Recoil

- I want to add this one in, I experimented a little with it a while ago and I think it addresses all the above issues.
- It's really easy to learn, and while all the state does technically live globally, it's totally opaque so seems scoped. Switching from local state to recoil state is (nearly) as simple as `useState` -> `useRecoilState`
- It feels very react-y
- However, it requires using experimental version of react and some of the api is subject to change. Personally I have no problem with this - version pinning would still work and facebook is using it in production.
- We would get other benefits from the experimental react features such as `useTransition` if we wanted
- No one anywhere has much experience with this and there is presumably less resources on how to use it (stackexchange questions, etc.)

#### `useContext`

- 100% scoped state, pretty easy to use
- Lose some features such as time travel and easy persistence
- Has a bigger potential for performance issues than other options

**Comment by lucaslcode** [comment]
Also, I am biased against global state because most of my limited previous experience is using Flutter for mobile apps, and the majority of state management solutions are totally scoped. For example, I recently used [Business Logic Components (BLoC) ](https://www.npmjs.com/package/@felangel/bloc) which I really like, and you don't need any local state anywhere, just do a self-contained bit of state for each feature/page/component. Wouldn't recommend it for react though.

So I will take into account that global state isn't necessarily a bad thing and it's just me :D

**Comment by amdwit** [comment]
Maybe you mean something like this? https://mobx-react.js.org/state-local
Or maybe more current: https://mobx.js.org/api.html#uselocalobservable
https://mobx.js.org/react-integration.html

**Comment by amdwit** [comment]
But recoil looks very promising!

**Comment by lucaslcode** [comment]
Yes looks like combining observables with react context is exactly what I mean. That pattern would imo be ideal for your group chats PR for example, where there is no reason for them to be in global state but you want to be able to access the group chat state deeply

**Comment by amdwit** [comment]
> This feels quite similar after moving the state into a Redux slice to me tbh, so I'm not sure what extra benefits we really gain trading Redux for MobX apart from your personal preference.

To me not: actions are also included, runtime type-checking, no extra theory needed (about actions/reducers/dispatchers/extrareducers/getState), you can change the values right away and observe, reasoning about it is much simpler. The last few days learning redux, even in the new way, came over to me as difficult.

> 
> Also it introduces generator functions which might increase the contribution curve to the project more. I thought relative ease of contribution important as that's why we even switched from Vue to React in the first place?

The only difference from using async/await is that async is replaced by `flow(function*` and await by `yield`. No other generator stuff is needed. And no knowledge about it is needed. It is just the same template for every async method. 

The reason for it is that MST makes sure the whole function will be marked as 'action'. We could also remove this rule of only changing state in actions and then we can just use async/await and also change our state where ever we want.

So I think this generator is not so important. We can easily just use async/await. We loose the strictness of allowing only changes from actions, but we can easily watch that ourselves, if we really care about that.

And if we go that way, we could also think about just using Mobx instead of Mobx-State-Tree.

And for junior contributors: with mobx things are easier than with redux. mobx-state-tree offers a local state solution that prevents too many ways to code the same. So that saves the seniors time for reviewing.

**Comment by amdwit** [comment]
I made a PR for the mobx alternative: #404 . The difference with the other demo PR is that no runtime type declaration is involved.

**Comment by darrenvong** [comment]
> Here are some of the issues (please add):
> 
> 1. Doesn't handle async natively very cleanly (requires thunks)
> 2. The store is global, and when to use component state vs the store is not always clear-cut
> 3. It has it's own code-feel/style that feels slightly alien to react (maybe that's more my opinion)
> 4. Difficult to learn

Weirdly, 1 and 3 feel like a conflict of interest even with all of these additional options for me. Apart from recoil, I'm not sure any of solutions proposed will fully satisfy 3. Although I'm unsure how recoil will solve 1 alone and given its relative infancy, I'd probably steer away from that for the time being and choose between Redux/MobX.

Also, it depends on what you mean by 3 - even if we were to roll our own and write everything with hooks/useEffects etc, we'd still need to use async functions anyway so I don't think thunks are that bad, especially as Redux toolkit has dealt with a lot of the rough edges that you'd need to manually deal with otherwise.

**Comment by amdwit** [comment]
About mobx: it changes everything within observable() into Proxy's. The getters of the proxies register in what components certain properties are read and then the setters will rerender the relevant components on change of properties.

**Comment by darrenvong** [comment]
I guess while we are at it, I'm gonna throw [React Query](https://react-query.tanstack.com/docs/quick-start) into the mix as well. It's not quite a full blown state management solution compared to Redux/MobX per se, but it's a pretty damn smart global cache that deals with fetching/invalidating/refreshing data for us out of the box with quite nice React integrations.

I haven't used it much myself but it's gaining popularity and from the quick start code, it looks quite "idiomatic" React to me. Together with the automatic refetch behaviour (customisable if this is too much), it might reduce boilerplate of us having to remember to update state after a message is sent for example. Reading state then works more or less the same as a regular `useState` hook.

The way I see us using Redux at the moment is we are essentially treating it as a cache for server side state to display stuff in the app. This could potentially solve problem 1 and 3 all in one go.

**Comment by amdwit** [comment]
I tried to implement React Query in the mobx demo and came upon:
- it is not easy to persist data
- I found the returning `isLoading` and `error` handy but not in all cases (button handlers).
- The code did not work as expected when the returned data is undefined(as all my model layer methods do)

So then I implemented and PR'd my own wrapper function for handling `loading` and `error`.

**Comment by darrenvong** [comment]
Do any of our options apart from Redux has an officially recommended option for persisting data? Not sure how important that is anyway, especially now that we've taken the auth token out. The data would constantly be changing so probably no harm in loading from scratch until that proves to be a performance bottleneck?

**Comment by darrenvong** [comment]
> * The code did not work as expected when the returned data is undefined(as all my model layer methods do)

What's the issue with always returning the data to the cache from a service call? I suspect then it's a case of reading the loading and error state as appropriate form `useQuery` in the UI components? Feels to me `useQuery` is meant to be the bridge between the service/API layer and the React UI

**Comment by amdwit** [comment]
There is no issue with it. But it does not fit in a mobx demo, as we would not need mobx anymore when using React Query. My preference goes to mobx with the 'action up, data down' thought. I prefer the idea of a view dev not having to know about service calls and caching. The model layer sits between the service layer and view layer. It also means that simple fetch calls can be made to the model like fire-and-forget: no return data needs to be handled in the view so almost all async code is in the model and model logic can be tested separately from react components. So I also prefer to have the state in one tree for easy persisting. And separate state logic from view logic because of object oriented vs functional.

**Comment by amdwit** [comment]
> Do any of our options apart from Redux has an officially recommended option for persisting data?

I do not think so about mobx and mst. But mobx-state-tree produces snapshots so persisting would be easy. domain state needs to be persisted, view state (`loading`/`error`) not. form state is in its own useForm solution.

**Comment by darrenvong** [comment]
> There is no issue with it. But it does not fit in a mobx demo, as we would not need mobx anymore when using React Query.

That was why I proposed it another alternative for exploration - I don't expect any of the options listed here to need to work together.

Since React Query seems to deal with all the various states between data is loading/available/errored out, it eliminates the need of thinking in terms of actions, and that's one layer of abstraction/indirection I'm willing to throw away (and it's one of the things I hate about Redux, since you're forced to stick with that pattern if you're using it). The `useQuery` stuff can be easily extracted into its own hooks (functions) so they can still become a standalone layer that can be tested in isolation.

It also has a whole bunch of interesting stuff like handling pagination which might come handy in future.

Then all that's left in the UI/view layer is reading and displaying data from the cache. All of this feels more beginner friendly to me as anyone with knowledge of how async/await/Promises work would be able to work with it. So I think definitely an alternative option worth thinking about!

**Comment by amdwit** [comment]
I tried to combine the things I like about React Query with mobx. That was not easily possible. That's why I said it did not fit.

What was not easy to do with React Query: persisting, injecting state . Both are difficult because the state is maintained within the component. Also some googling do not lead to a react-query plus persisting solution. So I would say we use mobx or MST for the global state and try to use react-query where possible.

**Comment by darrenvong** [comment]
For persisting, I believe the React Query state (they refer to as `queryCache` in their examples) can be serialised so we can do probably do something similar to MST with `JSON.stringify` and dump the state in localStorage. There's a [bunch of unofficial solutions](https://github.com/tannerlinsley/react-query/discussions/92) here and it seems like the library has improved since the discussion, namely it will mark data set with a pre-loaded state as stale so it will do refetching in the background when needed, which is quite neat.

As for injecting state, I assume you want this for testing purposes/to use with Storybook? I think the `queryCache.setQuery` function would let you do that.

**Comment by darrenvong** [comment]
Also since React Query is only a global cache, I don't see a problem trying to combine with Redux/MobX etc as it's not trying to get in the way at all, but it might just happen to solve a lot of pain we've faced with async operations and so free us to deal with app only state with Redux/MobX, or even with vanilla React state if it's not too complex.

**Comment by amdwit** [comment]
So would it be an idea to go forward with non-strict (no warnings about changes not in actions(so no generator async actions needed)) MST and gradually refactor to react-query?

**Comment by lucaslcode** [comment]
I haven't had time yet to experiment with your PRs - it's next on my list after finishing the location/jail stuff.

**Comment by lucaslcode** [comment]
I'm going to summarize/type out thoughts a bit.

We will have a ton of components which call the api, don't do very much logic and just display, with some actions that also perform an api call. In my opinion it would be really nice if we could do this:

```
const {loading, error, data}= model.asyncData();

const action = model.action;

return <>
{error && <Alert>{error}</Alert>}
<DataList loading={loading} data={data) />
<Button onClick={action} />
<\>;
```

That's just my preference, no dispatching and no global state (at least not transparently). Also no model logic in the view. This is very much mobx (but not mobx-state-tree) and probably (?) also doable with react-query.

However, not having global state, means you lose out on snapshots and easy persistence. We will probably need this for offline caching.

- It is probably possible to cache in the service layer. Especially since gRPC responses are binary-serializable. However, is it possible to do without the models being aware? What about knowing if we are offline or not?
- It is probably easier to cache if there is global state and/or snapshots. But this still could have the problem off caching logic going everywhere?
- React-query seems to have an internal global state you can access and there is [discussion about using that for offline caching here](https://github.com/tannerlinsley/react-query/discussions/92)
- If we only used react-query, we would still need a very tiny global state for knowing if the user is signed in (and maybe some client preferences later)

**Comment by darrenvong** [comment]
> That's just my preference, no dispatching and no global state (at least not transparently). Also no model logic in the view.

That's definitely my preference too - what you're describing there is something I'm more used to getting from using Apollo clients, which I think React Query has the closest API to that from what I've seen so far. Everything else we've considered, we kinda have to do that ourselves. 

> * If we only used react-query, we would still need a very tiny global state for knowing if the user is signed in (and maybe some client preferences later)

If this turns out to be the case, maybe `useState` with `useContext` together will suffice? They're unlikely to change a lot apart from between the user signing in and out, so shouldn't cause too many re-rendering issues.

> We will probably need this for offline caching.

I'm guessing this is to allow the app to be usable to some extent while they're offline, even though they wouldn't get the latest data?

**Comment by navandstokes** [comment]
I have to admit a lot of this is going over my head as I have mostly worked on projects where the UI is just reading data from cache, with very little global states. React Query would definitely be the most beginner friendly :) 

Coming from Next.js, I have used [SWR](https://swr.vercel.app/getting-started) which seems like pretty much the same as React Query. ~~Very sorry, can we consider this option as well?~~ Actually just found a [handy comparison chart](https://react-query-git-ce4fe79195bc3c2d81a564e80473188eb00f62e8.tannerlinsley.vercel.app/docs/comparison) from React Query.

**Comment by darrenvong** [comment]
As if React Query has been listening in to our conversations or something... they just released an official plugin for persisting the query cache to local storage in their latest major version update - https://react-query.tanstack.com/plugins/persist-localstorage!

**Comment by darrenvong** [comment]
After spinning up that demo with React Query for the friend list, thought I'll jot down a drawback I learnt about it too:
- It doesn't support normalised cache like Redux toolkit does. This means the same data (or subset of them) could be stored in multiple places. Although this might be intentional based off [this tweet thread](https://twitter.com/tannerlinsley/status/1283440927776796673), as React Query seems to promote invalidation patterns over managing synchronisation ourselves on the frontend.

**Comment by lucaslcode** [comment]
How would that affect us? Does that mean, for example, data from a query to get users from their ID wouldn't be shared across different parts of the app?

**Comment by darrenvong** [comment]
It would only affect us the most if we model things like this:

```
{
  "users": {
    "1": {
      "userId": 1,
      "userName": "aapeli",
      "displayName": "Aapeli",
      // some other user attributes...
    },
    "2": {
      "userId": 2,
      "userName": "lucas",
      "displayName": "Lucas"
      // some other user attributes...
    }
  },
  "friends": [
    {
      "userId": 1,
      "userName": "aapeli",
      "displayName": "Aapeli",
      // some other user attributes...
    },
    {
      "userId": 2,
      "userName": "lucas",
      "displayName": "Lucas"
      // some other user attributes...
    }
  ]
}
```

In this contrived example, we can see the friends list are referring to the same objects as user 1 and 2. In this scenario, React Query seems to recommend invalidating both the `["users", id]` and `friends` queries and let it refetch from the server to get the most up to date information when the app needs to display them, rather than trying to normalise it. Seems like an OK tradeoff to me as opposed to having to follow all the action dispatches, and we can always increase the stale time if we don't care about data getting out of sync for a short while to reduce server load if that's a problem.

We're not doing that in the case of the friend list feature in our current API though so it's fine for this feature. But do we do that anywhere else in our app?

**Comment by lucaslcode** [comment]
No, everything is fetched with IDs and is referred to by id. Which was annoying before, but looks like it could end up being a benefit.

**Comment by darrenvong** [comment]
I guess we resolved this now with React Query with the final refactor @lucaslcode did 🎉
