### ISSUE TITLE
Migration to backend-v2 endpoints

### ISSUE THREAD

**Issue by Tay0108** [Couchers-org/couchers#4103]
How should the process look like?
Can we use dev/staging for developing?
We can use either one but preferably staging.

Should we use https://github.com/Couchers-org/web-frontend/pull/165 PR or do it from scratch?
Since there was not many major features developed since creation of this PR we probably can use it.

We should create some dev branch for this migration and not merge to master until we are done to be able to do some fixes on master at the same time from other branches.

**Comment by darrenvong** [comment]
We had a follow-up chat earlier and it seems apparent that most of you who are onboarded to help with this effort are confused with how to fix the errors in the Couchers-org/web-frontend#165 PR with the generated client code.

Also from that discussion, it sparked some memory (from me) where I remember Guillermo and Jack (who attempted to integrate the new API with the web and mobile app respectively) mentioned that the generated types are not 100% accurate and requires some tweaks.

Based on those two points above, we agreed to abandon the code gen approach and start from scratch instead, hand annotating/typing the API responses as we work through the migration effort. I mentioned the downside being that there's a higher chance of human errors (from typing things wrong), but since the code gen isn't perfect and more opaque to work with which greatly hinders progress with our current skillset, hand writing the types is perhaps still the lesser of the two evils.

**Comment by wginsberg** [comment]
The branch we're using for this work is now `port-to-backend-v2`. Pull requests should target that instead of `master`.

**Comment by darrenvong** [comment]
Instead of jumping between issues, thought I'd make a note here (in this top level issue for ease of search) with the current sign up due to the current API limitations:
- User can't resume sign up if they don't do it all in one go, since the sign up flow token is not emailed to the user and only stored in localStorage at the moment. Hamish suggested this could potentially be resolved by flipping the ordering of how we do sign up to verify email -> log in -> fill in rest of profile. [Additional context in Slack conversation](https://couchersorg.slack.com/archives/C025XSM3NVB/p1671667578290909?thread_ts=1671655226.341349&cid=C025XSM3NVB)

**Comment by wginsberg** [comment]
> User can't resume sign up if they don't do it all in one go, since the sign up flow token is not emailed to the user and only stored in localStorage at the moment. Hamish suggested this could potentially be resolved by flipping the ordering of how we do sign up to verify email -> log in -> fill in rest of profile. [Additional context in Slack conversation](https://couchersorg.slack.com/archives/C025XSM3NVB/p1671667578290909?thread_ts=1671655226.341349&cid=C025XSM3NVB)

@darrenvong Hamish implemented this for the backend in https://github.com/Couchers-org/backend-v2/pull/71 - the frontend change is here https://github.com/Couchers-org/web-frontend/pull/268
