### ISSUE TITLE
UserSearch should have ability to filter by viewport/bounds

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#4513]
Part of #4129

Frontend part: #4081

**Comment by bakeiro** [comment]
**Actual situation:**
There is a backend function (service.search.userSearch) which receives as parameters the x,y coordinates, and search all the users in that point and 50Km around it

**Desired situation**
Instead of this, the backend should receive 4 points (the bounding box) and the sends back to frontend the list of users inside that box

**Notes:**
If the boundingBox it's to big (the size of a continent) this shouldn't be allowed, check this on the backend as well

**Comment by bakeiro** [comment]
![image](https://github.com/Couchers-org/couchers/assets/16777161/1f6691d4-3746-4fec-b59d-e96b3528322a)
