### ISSUE TITLE
Clarification on pages (places/guides/events)

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#502]
@ItsiW: could you please clarify in this issue the differences and similarities in pages (as a database table). At the moment pages covers places (points of interest/landmarks) and guides. Events have been left out into a different table, since we judged they'd be sufficiently different, but maybe they should be the same? What's your view on this? The conceptual plan at https://wiki.couchers.org/en/community/concept doesn't contain events.

**Comment by ItsiW** [comment]
At this point there are 3 different types of content:

## Main pages

A main page is the page associated with a cluster that is required for that cluster to exist. There is a 1-1 relationship between nodes and official clusters, and a 1-1 relationship between clusters and main pages. The main page of an official cluster is the information of the "Community page" that outlines need-to-knows about that place. All it requires is text, and it must be written by the admins of the official cluster (moderators of the node).

All main pages of official clusters are official. All main pages of non-official clusters are non-official (unsure if you are distinguishing this in the database).

Main pages do not require a geolocation (unofficial clusters (groups) don't have geolocations, and a geolocation point for nodes (e.g. city centre) can be put in the node information.

## Places

Places are points of interest, either owned by a user or a cluster. They require text and a geolocation. A place becomes official if its ownership is transferred to the admins of an official cluster, but is unofficial otherwise.

## Guides

Whereas main pages and places should convey objective information, guides allow for subjective information, or for extra detail that should not clutter the main guide. They essentially cover all other forms of content. They can be owned either by a user or a cluster, and are always unofficial. They do not require a geolocation.


# Events

Events are the combination of

- title
- text (description)
- geolocation
- thread
- starting time
- optional ending time
- relationship between users and the event

The page structure could be used to handle the title, text and geolocation, which could be handled by the page framework. Although I don't have an instinct either way whether we should do this or not.

One reason we may not want it is because the associated threads will be different. For all pages currently, there is an associated thread where users can suggest edits to the page. If we use a page for events, I don't imagine we'd want a thread associated with suggested edits for the event itself, but rather a thread that is just for people chatting about organising the event. Those threads will look and function quite differently. Essentially we don't need a thread associated with the "event page", but we do want one associated with the event table entry itself. Althuogh I imagine this might not be a huge difference in practice and could be handled quite easily

**Comment by lucaslcode** [comment]
Feel free to reopen this if necessary
