### ISSUE TITLE
Upgrade to React v18

### ISSUE THREAD

**Issue by nabramow** [Couchers-org/couchers#5167]
We need to upgrade to React v18 before we can upgrade Next.js to v13 and/or Material UI any further, so this should be the next upgrade priority.

Here is the migration guide for React v18:
https://react.dev/blog/2022/03/08/react-18-upgrade-guide

**Comment by darrenvong** [comment]
The Next.js docs for upgrading to v13 could be useful too: https://nextjs.org/docs/pages/building-your-application/upgrading/version-13

Although since we currently don't use much server-side features, I hope the upgrade should be fairly seamless 🤞 The only thing I can think of that _might_ need tweaking/breaks is the tiny middleware we wrote for re-directing users to the dashboard if they are already logged in, as I vaguely remember that to be still an experimental API when we used it for v12
