### ISSUE TITLE
Simplify docker-compose setup

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#518]
Currently there's too many containers in the main `docker-compose.yml` file. Some have reported that it's very slow and sluggish, and it confuses new devs. We should move the testing stuff and media container to another file. It also takes forever to run due to building yarn stuff inside docker.

Does anyone actually run the frontend inside docker?

**Comment by darrenvong** [comment]
Not for me personally for the React app - I start the project directly with yarn. Only been doing it for the Vue frontend out of convenience because it's already in the docker-compose, but I don't see why I can't start another terminal and run Vue with yarn too, considering I have noticed that tended to be the slowest docker image to build for me.
