### ISSUE TITLE
Hifi global/base styling and style guide

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#522]
Implement the "global" styles for pages to build off:
- [ ] Text styles
- [ ] Colour scheme (subject to change)
- [ ] Components
  - [ ] Button (is there only 1 type?)
  - [ ] List?
  - [ ] Others?

I also think we need some style guidelines to avoid either having to put the same style in heaps of different places, but conversely not having to change something in the "global"/component styles and then have layouts broken. 

For example:
- Do components like Button set their own margin? Or is it 0 and margin is set where it is used?

Any others that would be useful?

Also I had set a few overrides in `theme.js` eg. for `List` but I think maybe that was a Bad Idea, since other Mui components might use it with unexpected results.

**Comment by lucaslcode** [comment]
@darrenvong

**Comment by lucaslcode** [comment]
I guess what I want to avoid is the situation where we think "Actually, all text fields should have this style" change the component, and then break the style of some instances (which just happened heheh)

**Comment by darrenvong** [comment]
For button, I think it makes sense for it to only manage its internal spacing, so that's probably everything up to its border? This is so that we can port most styles across. If we start fixing margins on it, I bet there will be cases where the original margin we set wouldn't work and then it becomes a hack of styles further down just to override it 😅 

For lists, maybe it makes sense for it to manage space between list items and have a few "variants" depending on what the different spacing needs we have?

**Comment by lucaslcode** [comment]
Closed in #568
