### ISSUE TITLE
Address clean up from Nominatim

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#559]
In the legacy vue frontend, we stripped some parts of the address from Nominatim:

https://github.com/Couchers-org/couchers/blob/f95e212833a84d9c470e73530f78587676befc02/app/vue/src/components/EditableLocation.vue#L316-L334

This makes the display addresses a bunch nicer, so instead of:

```
Forbes Street, Macdonaldtown, Newtown, Sydney, Council of the City of Sydney, New South Wales, 2006, Australia
500, West 120th Street, Morningside Heights, Manhattan Community Board 9, Manhattan, New York County, New York, 10027, United States
```

We have:

```
Macdonaldtown, Sydney, Australia
Morningside Heights, Manhattan, New York, United States
```

**Comment by Tay0108** [comment]
The problem with this approach is that if we search for example "fa" we will get Italy, because there is a village named "Faedo", which is not really user-friendly. Therefore it should be done by query params to Nominatim, not filtered afterwards. Will take look into Nominatim docs. Also, maybe we should include villages as well? ;)
