### ISSUE TITLE
No way to get number of replies for top-level threads

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#665]
For example, the `Discussion` message has a `thread_id` and replies to the discussion have `num_replies` themselves, but there's no way to the the number of replies on the base thread.

**Comment by OmerBaddour** [comment]
My solution is pretty ugly as it entails a whole additional database query. However, this is forced, since the current querying uses `limit(page_size + 1)`, and I did not want to make extraneous changes in the pull request corresponding to this issue.

Some notes on threads in general:

Had a call with Aapeli, and we agreed that `threads.proto` and `threads.py` need some changes.

`threads.proto`'s API does not match the `thread-comment-reply` hierarchy described in the comments; it currently functions like Reddit comments - infinitely recursive. This can also be seen in the misleading API names and comments: `Reply` is used for both comments and replies, and `thread_id` can be the ID of both a thread or a comment.

Furthermore, the usage of `limit(page_size + 1)` to detect additional content is not great. It would be better to remove this limit, compare the raw size of the response with `page_size`, and also use the raw size to solve this issue.

Even better performance-wise would be adding a field to the `Threads` entity which stores the number of total number of responses to each thread, though Aapeli noted that cache coherency could be annoying to deal with. Nonetheless, if performance becomes a problem in the future, this could be a useful approach.
