### ISSUE TITLE
Put something in the dashboard until communities are done

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#756]
Also get rid of the "Create X" buttons

**Comment by lucaslcode** [comment]
@ItsiW  thoughts?

**Comment by andreaowu** [comment]
If this is just for soft launch, what about 
```
Welcome to Couchers! Thanks for your patience as we build out: 
- list of features that we're currently working on for beta launch
```

**Comment by ItsiW** [comment]
Yeah something simple like that is good for now. We might want a little explanation about transition from alpha for our current users. I'll work on some copy for beta.

For listing features I was thinking of creating a priority order page on the site which we can link to, that way we can signal things like hangouts and moderation tools are in the scope

**Comment by andreaowu** [comment]
When those are ready, please drop it here and I'll get it changed :)

**Comment by ItsiW** [comment]
Sorry for the delay. I've added some stuff from the alpha home page

Welcome to Couchers.org!

We're in the process of building out the platform, so we appreciate your patience as we create new features. 

If you've been here before, you may have noticed that some things have changed. That's because we're migrating from our early alpha version to our new beta version. If you were on the alpha version, don't worry, most of your profile data has been kept!

## Bugs

Bugs are to be expected, we are still in the testing phase and it's great that you're here to help with that. If you notice any bugs, please report them with the red button in the top right corner.

Please discuss anything else about the app on the [Community Forum](https://community.couchers.org).

## Features

We're working on a few more things before we launch, such as events, forums and community pages, as well as improved designs, and we'll let you know as those get released.

## Help out

If you're interested in helping out on this project, we'd love for you to [sign up](https://couchers.org/signup)! We are looking for people with all kinds of experience to help us build this amazing product.
