### ISSUE TITLE
Unread notification badge in messages is clipped on mobile

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#815]
![image](https://user-images.githubusercontent.com/32044095/111549496-2fa17a80-8774-11eb-85ed-ea4c333b6cb4.png)

**Comment by justjooshing** [comment]
There's not a lot of room for it to sit with in similar style as is set currently on small devices.
How do we think it looks with the default styling? I think having them overlaid (overlayed? overlain?) over the text doesn't look as clean.
![image](https://user-images.githubusercontent.com/60824744/111648912-c7967700-87fb-11eb-9550-14e8d82325f2.png)

Because even right: theme.spacing(-0.5) it still gets slightly cut off 
![image](https://user-images.githubusercontent.com/60824744/111649316-2a880e00-87fc-11eb-8bac-99ca0244e714.png)

Alternatively, we could increase the width of each of the tabs?

**Comment by lucaslcode** [comment]
How does it look with overflow allowed?
