### ISSUE TITLE
Group chat view doesn't scroll to bottom when you send a new message

### ISSUE THREAD

**Issue by darrenvong** [Couchers-org/couchers#827]
**Steps to reproduce**
1. Go to a group chat with enough messages such that scrolling is required
2. Send a new message

**Expected behaviour**
The message scroll view automatically scrolls down to the last message (either one you just sent or the latest message from another user)

**Actual behaviour**
The message scroll view is still stuck to the last message before you sent the message, so that you need to scroll down before you can see the new message(s).

**Comment by lucaslcode** [comment]
Also, on mobile when the keyboard opens, it reduces the vertical size of the window and the bottom message is no longer visible. I wonder if we can react to window resizing and, if the messages were scrolled to the bottom, re-scroll to the bottom.

**Comment by justjooshing** [comment]
@lucaslcode how can I see this on actual mobile? Or a different way instead of chrome dev tools (because I don't get the keyboard opening to see what I need to change on chrome)

**Comment by lucaslcode** [comment]
You could perhaps mimic it by reducing the vertical height of the window. 

I'm not sure if the same events get emitted for the keyboard though. It might require some investigation by connecting the Dev tools to chrome on a real device on the develop preview, and doing `monitorEvents(document.body)` in the console, and seeing what happens when the keyboard opens.

**Comment by lucaslcode** [comment]
Some googling tells me this might not work. Maybe you can do something with `onfocus` instead

**Comment by lucaslcode** [comment]
I have moved the milestone but keep working on it

**Comment by lucaslcode** [comment]
Closed in #849
