### ISSUE TITLE
Reset password skipped if user has no password

### ISSUE THREAD

**Issue by vrouilhac** [Couchers-org/couchers#846]
I noticed something while trying to reset the password. If i try to reset a password on an account that doesn't have set a password yet, the link redirect to a page that instantly say that the password has been successfully reset.

Step to reproduce : 

1 - Use or create an account that do not have a password set.
2 - Go to login page
3 - Click on reset password link
4 - Click on the link received on email

After that last step you should be redirected to the message. I think it would be better to ask for a new password.

**Comment by darrenvong** [comment]
@aapeliv This feels like a backend problem to me, as we could just not send the user an email if they already don't have a password? Also not sure why anyone would need to reset a password if they don't have one already as that wouldn't be mandated on login if that's the case.

**Comment by vrouilhac** [comment]
> @aapeliv This feels like a backend problem to me, as we could just not send the user an email if they already don't have a password? Also not sure why anyone would need to reset a password if they don't have one already as that wouldn't be mandated on login if that's the case.

Is the end expected behaviour to be able to access the app with registered account without password ? ( maybe this is just a feature avaible on development ? ) 

And also in the login screen we are not really able to see if the person has an account with password or not so the reset password button needs to be there.

**Comment by darrenvong** [comment]
> Is the end expected behaviour to be able to access the app with registered account without password ? ( maybe this is just a feature avaible on development ? )

Yes, by default everyone signs up without a password at the moment and can continue to login via a "magic link" sent to email. If they want to use a password, they can change it later on in their profile settings.

> And also in the login screen we are not really able to see if the person has an account with password or not so the reset password button needs to be there.

I believe this is intentional for security reasons, so people can't even guess at the moment if the username/email is associated to an account at the moment. Aapeli can probably better confirm this than I do.

**Comment by aapeliv** [comment]
Yes, what @darrenvong is saying is right.

Maybe at some point we'd like to show a user a different message if they never had a password (e.g. an error saying "your account has no password"), but that's really just a display thing. I think the behaviour is correct.

**Comment by lucaslcode** [comment]
I think backend should give an error if a user with no password tries to get a reset password link, considering you can type the username in, press log in, and you will know if they have a password or not

**Comment by aapeliv** [comment]
I don't think username enumeration or even finding out if a given username has a password or not is an issue. Whether a username exists or not is trivial to identify, and bulk requests should eventually be throttled with some kind of per-IP throttling if that starts being a problem.

I think emails are a bit more sensitive: we don't really want to disclose whether the owner of a given email address has an account registered on Couchers. I know this can currently be done with the sign in flow if the user has a password. I'm not sure in which cases people would wish to hide the fact that they've registered with that email, but email should be completely private information on the site. Maybe in the future we can disable login with email as a switch in security settings (and only allow login with username).

I know it's a bit cargo-culting to avoid any and all user enumeration attacks. I feel we don't need to hide certain usernames, but we should be careful with leaking email addresses. So I'd still prefer to minimize the number of email-leaking API calls.

Either way, I'm happy to change the logic to send a warning email instead of a password link if the user has no password.

**Comment by ShmuelTreiger** [comment]
What if attempting login with an email brings the user to password login no matter what, with a big notification that if they don't have a password they should click the link in the email (of course, if they don't have an account, then the email will let them know someone attempted to login despite no account). That way same behavior in all use cases.

**Comment by jesseallhands** [comment]
Duplicate, addressed by #4079
