### ISSUE TITLE
Split current users table into profile and users table

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#898]
Need to split off the profile data (often edited, large chunks of data, used only in few API calls) into a separate table from the core login/user info (often used, often joined across, rarely updated, small).

**Comment by lennartvanlaake** [comment]
I made a small design in drawio for how I would divide the data currently in the User table. My philosophy is that a core entity such as a user should be stable and small, because it is used in many places and has many dependencies. Data that does not intrinsically belong to that entity should live in separate tables which are separated per domain for which that data is used. I know I am going to get a lot of hate for the amount of added tables, but I think having clearly separated tables creates a clearer and more maintainable app than infinitly growing tables which are used for multiple things. The link to the doc is: https://drive.google.com/file/d/1ursZ0drssOg2WecvQj7WaKJXbukzngWZ/view?usp=sharing

I would suggest splitting the API-calls to separate calls for the user itself (name, location, etc), the profile (stuff a user wrote about himself) and the hosting preferences (things a user writes about his house)
