### ISSUE TITLE
Simplify bug reporting tool

### ISSUE THREAD

**Issue by ItsiW** [Couchers-org/couchers#992]
We should only have 3 fields:

1. Brief description of the bug (title)
2. What did you do to trigger the bug?
3. What happened? What should have happened?

**Comment by aapeliv** [comment]
While the bug reporter is being touched: I think it'd also be good for it to disappear after the bug is reported (or at least for the fields to be emptied). Currently it stays open with the text still in. There is also no cancel button, so it might not be 100% obvious you have to click outside the box to close it. Would be good for it to be a bit wider too?

**Comment by jesseallhands** [comment]
Would it be helpful to devs to also allow uploading of images? I usually just log in on GitHub, find the bug I just reported and post the screenshot there, but it might be more helpful if people could upload a screenshot directly within the bug reporting tool.

**Comment by aapeliv** [comment]
Yes, but it's quite complicated, so we'll leave it til later
